version: '1'
services:
  postgres:
    container_name: pg_db
    image: postgres:latest
    environment:
      POSTGRES_USER: notes_app_user
      POSTGRES_PASSWORD: notes_app_password
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
  nodejs:
    build: .
    ports:
      - "4444:4444"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://notes_app_user:notes_app_password@postgres:5432/notes_db
volumes:
  postgres_data: